src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $login;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

	/**
	 * @ORM\Column(type="json")
	 */
	private $roles = [];

	/**
	 * User constructor.
	 */
	public function __construct()
	{
		$this->roles = array('ROLE_USER');
	}

	/**
	 * @return int|null
	 */
	public function getId(): ?int
    {
        return $this->id;
    }

	/**
	 * @return string|null
	 */
    public function getLogin(): ?string
    {
        return $this->login;
    }

	/**
	 * @param string $login
	 * @return $this
	 */
    public function setLogin(string $login): self
    {
        $this->login = $login;
        return $this;
    }

	/**
	 * @return string|null
	 */
    public function getPassword(): ?string
    {
        return $this->password;
    }

	/**
	 * @param string $password
	 * @return $this
	 */
    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

	/**
	 * A visual identifier that represents this user.
	 *
	 * @see UserInterface
	 */
	public function getUsername(): string
	{
		return (string) $this->login;
	}

	/**
	 * @see UserInterface
	 */
	public function getRoles(): array
	{
		$roles = $this->roles;
		// guarantee every user at least has ROLE_USER
		$roles[] = 'ROLE_USER';
		return array_unique($roles);
	}

	/**
	 *
	 */
	public function setRoles(array $roles): self
	{
		$this->roles = $roles;
		return $this;
	}

	public function isPasswordValid(UserInterface $user, string $raw){

	}



	/**
	 * @see UserInterface
	 */
//	public function getPassword()
//	{
//		// not needed for apps that do not check user passwords
//	}
	/**
	 * @see UserInterface
	 */
	public function getSalt()
	{
		// not needed for apps that do not check user passwords
	}
	/**
	 * @see UserInterface
	 */
	public function eraseCredentials()
	{
		// If you store any temporary, sensitive data on the user, clear it here
		// $this->plainPassword = null;
	}

}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/css/login/login.css">
{% endblock %}

{% block body %}
<form class="form-signin" method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputLogin">Login</label>
    <input type="text" value="{{ last_username }}" name="login" id="inputLogin" class="form-control" autocomplete="username" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_row(form.login) }}
    {{ form_row(form.password.first) }}
    {{ form_row(form.password.second) }}

    <button type="submit">Register!</button>
    {{ form_end(form) }}
{% endblock %}